name: Build PJSK-MultiGUI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    name: Build on Linux
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip build-essential libgl1 libx11-dev

      - name: Install Python dependencies
        run: |
          pip3 install Cython==0.29.32
          pip3 install -r requirements.txt pyinstaller

      - name: Build local Cython module
        run: |
          cd monotonic_align
          python3 setup.py build_ext --inplace

      - name: Build with PyInstaller
        run: pyinstaller --clean PJSK-MultiGUI.spec

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: PJSK-Linux
          path: dist/

  build-windows:
    runs-on: windows-2022
    name: Build on Windows 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install Cython==0.29.32
          pip install -r requirements.txt pyinstaller
      
      - name: Build local Cython module
        run: |
          cd monotonic_align
          python setup.py build_ext --inplace

      - name: Build with PyInstaller
        run: pyinstaller PJSK-MultiGUI.spec

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: PJSK-Windows
          path: dist/

  build-macos-intel:
    runs-on: macos-13
    name: Build on macOS Intel (target 13.0)
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install Cython==0.29.32
          pip install -r requirements.txt pyinstaller
        
      - name: Build local Cython module
        run: |
          cd monotonic_align
          python setup.py build_ext --inplace

      - name: Build with PyInstaller
        run: pyinstaller PJSK-MultiGUI.spec

      - name: Compress .app bundle
        run: |
          ditto -c -k --sequesterRsrc --keepParent dist/PJSK-MultiGUI.app PJSK-MultiGUI-macOS.zip

      - name: Upload compressed .app zip
        uses: actions/upload-artifact@v4
        with:
          name: PJSK-macOS-Intel-Zip
          path: PJSK-MultiGUI-macOS.zip

  build-macos-arm:
    runs-on: macos-14
    name: Build on macOS ARM (target 11.0)
    env:
      MACOSX_DEPLOYMENT_TARGET: '11.0'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install Cython==0.29.32
          pip install -r requirements.txt pyinstaller
      
      - name: Build local Cython module
        run: |
          cd monotonic_align
          python setup.py build_ext --inplace

      - name: Build with PyInstaller
        run: pyinstaller PJSK-MultiGUI.spec
      
      - name: Compress .app bundle
        run: |
          ditto -c -k --sequesterRsrc --keepParent dist/PJSK-MultiGUI.app PJSK-MultiGUI-macOS.zip

      - name: Upload compressed .app zip
        uses: actions/upload-artifact@v4
        with:
          name: PJSK-macOS-ARM-Zip
          path: PJSK-MultiGUI-macOS.zip