name: Build PJSK-MultiGUI

on:
  push:
    paths:
      - '**.py'
      - '**.spec'
      - requirements.txt
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    name: Build on Linux (Ubuntu 20.04 via Docker)
    steps:
      - uses: actions/checkout@v4

      - name: Build in Ubuntu 20.04 container
        run: |
          docker run --rm -v "$PWD":/app -w /app ubuntu:20.04 /bin/bash -c "
            apt update &&
            apt install -y python3 python3-pip build-essential libgl1 libx11-dev &&
            pip3 install Cython==0.29.32 &&
            pip3 install -r requirements.txt pyinstaller &&
            pyinstaller PJSK-MultiGUI.spec
          "

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: PJSK-Linux
          path: dist/

  build-windows:
    runs-on: windows-2022
    name: Build on Windows 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install Cython==0.29.32
          pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller PJSK-MultiGUI.spec

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: PJSK-Windows
          path: dist/

  build-macos-intel:
    runs-on: macos-13
    name: Build on macOS Intel (target 10.15)
    env:
      MACOSX_DEPLOYMENT_TARGET: '10.15'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install Cython==0.29.32
          pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller PJSK-MultiGUI.spec

      - name: Upload macOS Intel artifact
        uses: actions/upload-artifact@v4
        with:
          name: PJSK-macOS-Intel
          path: dist/

  build-macos-arm:
    runs-on: macos-14
    name: Build on macOS ARM (target 11.0)
    env:
      MACOSX_DEPLOYMENT_TARGET: '11.0'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install Cython==0.29.32
          pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller PJSK-MultiGUI.spec

      - name: Upload macOS ARM artifact
        uses: actions/upload-artifact@v4
        with:
          name: PJSK-macOS-ARM
          path: dist/